FROM --platform=linux/amd64 rust:latest 

RUN apt update && apt upgrade -y
RUN cargo install chia 
  
WORKDIR /chia_rust_utils

COPY ../chia_rs /chia_rs
 
  

CMD ["cargo", "build", "--release", "--target=x86_64-unknown-linux-gnu"]